-- Table: public.Achievements

-- DROP TABLE public."Achievements";

CREATE TABLE public."Achievements"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "LinkIMG" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Achievements_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public."Achievements"
    OWNER to postgres;

CREATE TABLE public."Project"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "idTL" integer NOT NULL,
    CONSTRAINT "Project_pkey" PRIMARY KEY (id),
    CONSTRAINT "idTL_FK" FOREIGN KEY ("idTL")
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Project"
    OWNER to postgres;
-- Index: fki_IdTL

-- DROP INDEX public."fki_IdTL";

CREATE INDEX "fki_IdTL"
    ON public."Project" USING btree
    ("idTL" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public."Role"
(
    "Role" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Role_pkey" PRIMARY KEY ("Role")
)

TABLESPACE pg_default;

ALTER TABLE public."Role"
    OWNER to postgres;

CREATE TABLE public."Task"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "idProject" integer NOT NULL,
    CONSTRAINT "Task_pkey" PRIMARY KEY (id),
    CONSTRAINT "idProject_FK" FOREIGN KEY ("idProject")
        REFERENCES public."Project" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Task"
    OWNER to postgres;
-- Index: fki_idProject_FK

-- DROP INDEX public."fki_idProject_FK";

CREATE INDEX "fki_idProject_FK"
    ON public."Task" USING btree
    ("idProject" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public."User"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Surname" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Patronymic" character varying(50) COLLATE pg_catalog."default",
    "Birthday" date NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "Password" text COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "User_pkey" PRIMARY KEY (id),
    CONSTRAINT "Role_FK" FOREIGN KEY ("Role")
        REFERENCES public."Role" ("Role") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."User"
    OWNER to postgres;
-- Index: fki_Role_FK

-- DROP INDEX public."fki_Role_FK";

CREATE INDEX "fki_Role_FK"
    ON public."User" USING btree
    ("Role" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public."User-Achievements"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "idUser" integer NOT NULL,
    "idAchievements" integer NOT NULL,
    CONSTRAINT "User-Achievements_pkey" PRIMARY KEY (id),
    CONSTRAINT "idAchievements_FK" FOREIGN KEY ("idAchievements")
        REFERENCES public."Achievements" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "idUser_FK" FOREIGN KEY ("idUser")
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."User-Achievements"
    OWNER to postgres;
-- Index: fki_idAchievements_FK

-- DROP INDEX public."fki_idAchievements_FK";

CREATE INDEX "fki_idAchievements_FK"
    ON public."User-Achievements" USING btree
    ("idAchievements" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_idUser_FK

-- DROP INDEX public."fki_idUser_FK";

CREATE INDEX "fki_idUser_FK"
    ON public."User-Achievements" USING btree
    ("idUser" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public."User-Task"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "idUser" integer NOT NULL,
    "idTask" integer NOT NULL,
    CONSTRAINT "User-Task_pkey" PRIMARY KEY (id),
    CONSTRAINT "idTask_FK" FOREIGN KEY ("idTask")
        REFERENCES public."Task" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "idUser_FK" FOREIGN KEY ("idUser")
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."User-Task"
    OWNER to postgres;
-- Index: fki_idTask_FK

-- DROP INDEX public."fki_idTask_FK";

CREATE INDEX "fki_idTask_FK"
    ON public."User-Task" USING btree
    ("idTask" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_idUsr_FK

-- DROP INDEX public."fki_idUsr_FK";

CREATE INDEX "fki_idUsr_FK"
    ON public."User-Task" USING btree
    ("idUser" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public."WorkingTime"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "idUser" integer,
    "idTask" integer,
    "StartTime" timestamp without time zone,
    "EndTime" timestamp without time zone,
    CONSTRAINT "WorkingTime_pkey" PRIMARY KEY (id),
    CONSTRAINT "FK_idTask" FOREIGN KEY ("idTask")
        REFERENCES public."Task" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "FK_idUser" FOREIGN KEY ("idUser")
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "idTask_FK" FOREIGN KEY ("idTask")
        REFERENCES public."Task" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "idUser_FK" FOREIGN KEY ("idUser")
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."WorkingTime"
    OWNER to postgres;
-- Index: fki_FK_idTask

-- DROP INDEX public."fki_FK_idTask";

CREATE INDEX "fki_FK_idTask"
    ON public."WorkingTime" USING btree
    ("idTask" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_FK_idUser

-- DROP INDEX public."fki_FK_idUser";

CREATE INDEX "fki_FK_idUser"
    ON public."WorkingTime" USING btree
    ("idUser" ASC NULLS LAST)
    TABLESPACE pg_default;

                                